### ISSUE TITLE
Разработка модуля Instagramm

### ISSUE THREAD

**Issue by AntonKiselyov** [AntonKiselyov/FriendiGram#14]
Вам предстоит разработать модуль взаимодействия с социальной сетью Instagram

Модуль долженн делать:
1. Авторизацию пользователя
2. Забор данных с сервера (по поводу того какие данные - проконсультируетесь с этим вопросом у Александра Переверзева)
3. Сохранять данные в БД
4. Обрабатывать ошибки

5. Быть готовым писать тесты (потребуется позже)

Срок сдачи: до понедельника

**Comment by SergKlimov** [comment]
Done
