### ISSUE TITLE
Разработка модулей для получения изображения от камеры и нанесения на данное изображение будущих лейблов.

### ISSUE THREAD

**Issue by AntonKiselyov** [AntonKiselyov/FriendiGram#3]
Вам, /сс @SergKlimov , поручается разработка модулей нанесения анимационных лейблов на изображение от камеры мобильного устройства, а для этого необходимо:
1. Разработать модуль для работы с камерой
2. Разработать класс Лейбл, который будет отображать всю необходимую информацию, при этом при необходимости его можно было бы легко менять, как внутреннее содержание так и внешнее
3. Быть готовым прикручивать в дальнейшем геолокационные модули

Необходимые средства: Активити, View, Camera Classes and other

Срок сдачи: 5.10.2015

**Comment by SergKlimov** [comment]
Job done, man
