### ISSUE TITLE
Разработка службы интеграции с соц сетями

### ISSUE THREAD

**Issue by AntonKiselyov** [AntonKiselyov/FriendiGram#4]
Вам. @Pereverzev-Alexander , Необходимо разработать модули для интеграции с социальными сетями
Для этого нужно:
1. Разработать архитектуру службы
2. Разработать сервис работающий в отдельном процессе, с асинхронным режимом работы
3. Разработать модули интеграции с Instagramm, VK
4. Разработать механизмы авторизации

Предварительный прототип хотелось бы видеть 23-25 октября, который бы содержал сервис, одну из соц сетей, и хранилище данных

Необходимые тюториалы:
Service:
Сайт андроид разработчика, уроки по Андроид

Вконтакте:

https://vk.com/dev/android_sdk
http://habrahabr.ru/post/209974/
https://github.com/thest1/Android-VKontakte-SDK
http://interosite.ru/articles/rabota-s-api-vkontakte-v-android

Инстаграмм:

https://instagram.com/developer/
http://www.mobilab.ru/androiddev/instagraminandroid.html

Twitter:

https://dev.twitter.com/mopub/android
https://docs.fabric.io/android/twitter/index.html
http://habrahabr.ru/post/114544/
https://twittercommunity.com/t/build-android-applications-with-twitter/5822
http://blogs.shephertz.com/2014/05/15/how-to-integrate-twitter-in-your-android-app/

Хранилище:
http://alvinalexander.com/android/android-tutorial-preferencescreen-preferenceactivity-preferencefragment
http://developer.alexanderklimov.ru/android/preference.php
http://developer.alexanderklimov.ru/android/preferences_framework.php
База данных SQLite

**Comment by Pereverzev-Alexander** [comment]
Готово!
