### ISSUE TITLE
Разработка модулей Twitter

### ISSUE THREAD

**Issue by AntonKiselyov** [AntonKiselyov/FriendiGram#5]
Вам, @Pereverzev-Alexander   , Необходимо начать разработку модулей для интеграции с социальными сетями  Twitter,
Модуль должен:
1. Работать в сервисе
2. Производить авторизацию пользователя
3. Получать данные от сервера и записывать их в хранилище

Помочь создать временное хранилище

Предварительтный прототип хотелось бы видеть: через две недели

Необходимые тюториалы:
1. Android service
2. Twitter:

https://dev.twitter.com/mopub/android
https://docs.fabric.io/android/twitter/index.html
http://habrahabr.ru/post/114544/
https://twittercommunity.com/t/build-android-applications-with-twitter/5822
http://blogs.shephertz.com/2014/05/15/how-to-integrate-twitter-in-your-android-app/

**Comment by Pereverzev-Alexander** [comment]
Done

**Comment by Pereverzev-Alexander** [comment]
Done
